### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by andretadeu**
I've cleaned the code a little bit.

### CODE REVIEW

**Comment by tedeling** [comment]
It seems that the trunk itself is broken due to changes in the parent. Once the develop branch is merged into master it should be fine.

**Comment by tedeling** [comment]
I reverted the change, some things:
 - the next release version is 1.4.2, not sure why you updated the version to 1.5.0;
 - ProjectAssignmentType is living in the repository layer but getResourceKeyForProjectAssignmentType is a typical method for the UI layer;
 - TimesheetEntry, why change the float with bigdecimals? Float is already overkill or was it because the postgresql type switch from real to decimal (9,3) (which is a good thing btw);
 - in the scenarios (AssignmentAdminScenario) you changed to assign_user_to_multiple_projects_at_once to camel case assignUserToMultipleProjectsAtOnce. Now I know that using underscores is a no-no in Java but I prefer the exception in tests. When describing the behavior that a test tests you end up with longer sentences than your average method name length. To make it a bit more readable I prefer to use underscores rather than camel case;
- why the switch from pom to jar packaging in eHour-standalone?
- what's timesheet segment?
- did you manage to get sonar profiling on scala using cobertura?

**Comment by andretadeu** [comment]
Thies,

Sorry for the inconvenience. I tried to pull a minor refactoring, but I
kept commiting and the pull request remained open, appending the commits I
did not want to be merged. I am not sure that I pull that changes due to
the following reasons:
- I have to develop a new page to register the work time in intervals, for
instance: Monday, 2015-02-09, 8:00 - 12:00; Monday, 2015-02-09 13:00-17:00.
For this specific page, people can register entries such as: Monday,
2015-02-09, 8:07 - 1159; Monday, 2015-02-09 13:01-17:20. All the entries
should be summed up and the result should be exact.
- I am working with a co-worker to expose REST services for a future
development of an Android client application.

For the comments about the code:
- ProjectAssignmentType seems to be an enumeration of types of project
assignments.
- I needed to generate the jar in eHour-standalone and I changed to jar,
but I did not want it in the pull request.
- I will use the TimesheetEntrySegment to persist the work time intervals.
- The sonar-scala-plugin is not been developed for a while. I tried to use
it, however the plugin did not work.

About the version, I am diverging from your project and I am not sure if
you want all these changes.

Sorry again,

Andre Tadeu de Carvalho

**Comment by tedeling** [comment]
I saw the pull when you initially did that and that looked nice but it grew a bit bigger :)

- I am more than interested in the REST and Android part. Do you have a timeline for when you start with it?
- ProjectAssignmentType is indeed a numeration, there's no need anymore to make it a db table. Could you use some refactoring

If you can make a new pull request for the change to an enum plus jdk7 closeable, that'd be nice. What's the URL where your project is livign?

**Comment by andretadeu** [comment]
I asked a co-worker to develop the REST part and he started doing so
yesterday, using Spring MVC (Android clients can use either Spring to
consume REST services or Retrofit).

About the refactoring of ProjectAssignmentType I can do ASAP.

The URL of my project is https:// github.com/andretadeu/ehour

There are some unfinished classes, since I am learning on how to create the
pages using Wicket and integrating the new code with the existing one.
Em 10/02/2015 19:25, "Thies Edeling" <notifications@github.com> escreveu:

**Comment by andretadeu** [comment]
Thies,

> If you can make a new pull request for the change to an enum plus jdk7
closeable, that'd be nice. What's the URL where your project is livign?

I created another fork in https://github.com/andretc83/ehour to make the
pull requests to:
- Change ProjectAssignmentType to an enum.
- Use JDK 7 try-with-resources.
- Finish eHour portuguese language translations.
- Create the REST services. I suggest that the name of the REST packages
should end with .rest.

Regards,

André Tadeu de Carvalho

2015-02-10 19:24 GMT-02:00 Thies Edeling <notifications@github.com>:

**Pull request merged**
